name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Kul att du vill bidra! Vi ska titta på ditt ärende så snart som möjligt."
          pr-message: "Tack för din pull request! Vi kommer att granska din kod och återkomma."
